@baseUrl = http://localhost:3333
@authToken = {{authenticate_seller.response.body.accessToken}}

# @name register_seller
POST {{baseUrl}}/sellers
Content-Type: application/json

{
	"name": "Teste 2",
  "phone": "1234567892",
	"email": "teste2@teste.com.br",
  "avatarId": null,
	"password": "123456",
  "passwordConfirmation": "123456"  
}

###

# @name edit_seller
PUT {{baseUrl}}/sellers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"name": "Teste 1 edited",
  "phone": "0123456789",
	"email": "edited@teste.com.br"
}

###

# @name get_seller_profile
GET {{baseUrl}}/sellers/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name authenticate_seller
POST {{baseUrl}}/sellers/sessions
Content-Type: application/json

{
	"email": "teste1@teste.com.br",
	"password": "123456"
}

###

# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Category 2"
}

###

# @name fetch_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Product 2",
  "description": "A detailed product 2 description",
  "priceInCents": 2000,
  "categoryId": "0d5e54b4-ac6d-47e6-957b-3e12af76bc34",
  "attachmentsIds": []
}

###

# @name fetch_recent_products
GET {{baseUrl}}/products?page=1&search=3&status=available
Content-Type: application/json
Authorization: Bearer {{authToken}}