@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/sellers
Content-Type: application/json

{
	"name": "Teste 1",
    "phone": "123456789",
	"email": "teste1@teste.com.br",
    "avatarId": null,
	"password": "123456",
    "passwordConfirmation": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sellers/sessions
Content-Type: application/json

{
	"email": "teste1@teste.com.br",
	"password": "123456"
}